# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"3\n\x0eMessageRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"8\n\x0fMessageResponse\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x13\n\x0bserver_note\x18\x02 \x01(\t\"8\n\x07mathReq\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\x12\x11\n\toperation\x18\x03 \x01(\t\"@\n\x08mathResp\x12\x14\n\x0c\x66inal_answer\x18\x01 \x01(\x02\x12\x10\n\x08received\x18\x02 \x01(\x08\x12\x0c\n\x04note\x18\x03 \x01(\t\"\x1b\n\x07nameReq\x12\x10\n\x08username\x18\x01 \x01(\t\"-\n\x08nameResp\x12\x10\n\x08received\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"-\n\x0bTodoRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04task\x18\x02 \x01(\t\"C\n\x0cTodoResponse\x12\r\n\x05saved\x18\x01 \x01(\x08\x12\x13\n\x0btask_number\x18\x02 \x01(\x05\x12\x0f\n\x07summary\x18\x03 \x01(\t2\xd1\x01\n\x0b\x43hatService\x12:\n\x0bSendMessage\x12\x14.chat.MessageRequest\x1a\x15.chat.MessageResponse\x12\'\n\x06\x64oMath\x12\r.chat.mathReq\x1a\x0e.chat.mathResp\x12+\n\nmotivation\x12\r.chat.nameReq\x1a\x0e.chat.nameResp\x12\x30\n\x07\x61\x64\x64Todo\x12\x11.chat.TodoRequest\x1a\x12.chat.TodoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=20
  _globals['_MESSAGEREQUEST']._serialized_end=71
  _globals['_MESSAGERESPONSE']._serialized_start=73
  _globals['_MESSAGERESPONSE']._serialized_end=129
  _globals['_MATHREQ']._serialized_start=131
  _globals['_MATHREQ']._serialized_end=187
  _globals['_MATHRESP']._serialized_start=189
  _globals['_MATHRESP']._serialized_end=253
  _globals['_NAMEREQ']._serialized_start=255
  _globals['_NAMEREQ']._serialized_end=282
  _globals['_NAMERESP']._serialized_start=284
  _globals['_NAMERESP']._serialized_end=329
  _globals['_TODOREQUEST']._serialized_start=331
  _globals['_TODOREQUEST']._serialized_end=376
  _globals['_TODORESPONSE']._serialized_start=378
  _globals['_TODORESPONSE']._serialized_end=445
  _globals['_CHATSERVICE']._serialized_start=448
  _globals['_CHATSERVICE']._serialized_end=657
# @@protoc_insertion_point(module_scope)
