syntax = "proto3";

package chat;


service ChatService {
    rpc SendMessage (MessageRequest) returns (MessageResponse);
    rpc doMath (mathReq) returns (mathResp);
    rpc motivation (nameReq) returns (nameResp);
    rpc addTodo (TodoRequest) returns (TodoResponse);
}

message MessageRequest {
    string username = 1;
    string content = 2;
}

message MessageResponse {
    bool received = 1;
    string server_note= 2;
}

message mathReq {
    int32 num1 = 1;
    int32 num2 = 2;
    string operation = 3;
}

message mathResp {
    float final_answer = 1;
    bool received = 2;
    string note = 3;
}

message nameReq{
    string username = 1;
}

message nameResp {
    bool received = 1;
    string message = 2;
}

message TodoRequest {
    string username = 1;
    string task = 2;
}

message TodoResponse {
    bool saved = 1;
    int32 task_number = 2;
    string summary = 3;
}